"""Generate persistent storage configuration inside the mounted target."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .btrfs import BTRFS_SUBVOLUMES
from .command import CommandRunner
from .model import Filesystem
from .steps import FailurePolicy, InstallContext


@dataclass
class ConfigureStorageStep:
    runner: CommandRunner
    id: str = "configure-storage"
    title: str = "Configure persistent filesystems and swap"
    failure_policy: FailurePolicy = FailurePolicy.FATAL
    progress_weight: int = 2
    destructive: bool = False

    def preflight(self, context: InstallContext) -> None:
        self.runner.require_commands(("blkid",))

    def execute(self, context: InstallContext) -> None:
        target = _target(context)
        devices = context.values["partition_devices"]
        uuids = {
            name: self.runner.run(
                ("blkid", "-s", "UUID", "-o", "value", device),
                timeout=10,
            ).stdout.strip()
            for name, device in devices.items()
            if name in {"root", "efi-system", "swap"}
        }
        missing = sorted(name for name, value in uuids.items() if not value)
        if missing:
            raise RuntimeError(
                "Missing filesystem UUID: " + ", ".join(missing)
            )

        if context.plan.storage.filesystem is Filesystem.BTRFS:
            root_lines = "".join(
                f"UUID={uuids['root']} {subvolume.mount_point} btrfs "
                f"{subvolume.mount_options} 0 0\n"
                for subvolume in BTRFS_SUBVOLUMES
            )
        else:
            root_lines = (
                f"UUID={uuids['root']} / ext4 defaults,noatime 0 1\n"
            )

        fstab = (
            "# /etc/fstab generated by Andiora Installer\n"
            f"{root_lines}"
            f"UUID={uuids['efi-system']} /boot/efi vfat defaults,noatime 0 1\n"
            f"UUID={uuids['swap']} none swap sw,pri={context.plan.swap.disk_priority} 0 0\n"
        )
        etc = target / "etc"
        etc.mkdir(parents=True, exist_ok=True)
        (etc / "fstab").write_text(fstab, encoding="utf-8")

        # Keep zram declarative and explicit. This is the format consumed by
        # andiora-swap-config; omitting a fixed size preserves 50%-of-RAM.
        defaults = etc / "default"
        defaults.mkdir(parents=True, exist_ok=True)
        (defaults / "andiora-zram").write_text(
            "ZRAM_ENABLED=yes\n"
            f"ZRAM_ALGORITHM={context.plan.swap.zram_algorithm}\n"
            f"ZRAM_PRIORITY={context.plan.swap.zram_priority}\n",
            encoding="utf-8",
        )

    def verify(self, context: InstallContext) -> None:
        fstab = (_target(context) / "etc/fstab").read_text(encoding="utf-8")
        required = ("/boot/efi vfat", " none swap ", "UUID=", " / ")
        missing = [value for value in required if value not in fstab]
        if missing:
            raise RuntimeError("Generated fstab failed verification")
        if f"pri={context.plan.swap.disk_priority}" not in fstab:
            raise RuntimeError("Disk swap priority is missing from fstab")

    def cleanup(self, context: InstallContext) -> None:
        return None


def _target(context: InstallContext) -> Path:
    target = context.values.get("target")
    if not isinstance(target, Path):
        raise RuntimeError("Target filesystem is not mounted")
    return target
